version: '3.8'

services:
  mysql:
      image: mysql:latest 
      container_name: mysql_db
      ports:
        - 3306:3306
      expose:
        - "3306"
      cap_add:
        - SYS_NICE # CAP_SYS_NICE
      volumes:
        - ./data:/var/lib/mysql
        - ./conf-mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=plan-gpt-db
        - MYSQL_DATABASE=mydb
      restart: unless-stopped

